### ISSUE TITLE
Progress speed

### ISSUE THREAD

**Issue by Dduvacher** [rcaferati/react-awesome-button#10]
Can we manage the speed of the progress button to maki it homogeneous ?

**Comment by rcaferati** [comment]
Hey. You can control it through the `loading-transition-timing`, `loading-transition-speed` and `loading-transition-end-speed` CSS custom properties or SASS variables. Checkout [this file](https://github.com/rcaferati/react-awesome-button/blob/master/src/styles/base/custom-properties.scss).
