### ISSUE TITLE
How to reset state for AwesomeButtonProgress ?

### ISSUE THREAD

**Issue by alexandrzavalii** [rcaferati/react-awesome-button#11]
If AwesomeButtonProgress fails, the button is disabled.
How to reset it and to make it enabled again ?

**Comment by rcaferati** [comment]
Hey @alexandrzavalii. You can checkout the progress handling strategy on the storybook (here)[https://caferati.me/demo/react-awesome-button/storybook/?knob-size=large&knob-type=primary&knob-text=Progress&selectedKind=AwesomeButtonProgress&selectedStory=Success&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs].

Generally it goes like:

```
<Button
    ...
    onPress={(next) => {
        ...
        // on success
        next();
        // on error
        next(false, 'Erros message');
    }}
/>
```

**Comment by SLAYER-CODE** [comment]
react-native:

`                           nextt!(()=>{  #Code  })
`
