### ISSUE TITLE
How to Call Error on AwesomeButtonProgress

### ISSUE THREAD

**Issue by njho** [rcaferati/react-awesome-button#13]
Hi,

The docs have the following:

```
 <AwesomeButtonProgress
                            action={(element, next) => this.doSomethingThenCall(next)}
                            type={'secondary'}>LIVE! Request An Update</AwesomeButtonProgress>
```

How would we pull up the ErrorLabel in case of failure?

**Comment by rcaferati** [comment]
Hey @njho. You can checkout the error handling on the storybook [here](https://caferati.me/demo/react-awesome-button/storybook/?knob-loadingLabel=Wait%20for%20it..&knob-resultLabel=Done%21&knob-releaseDelay=1000&knob-size=large&knob-type=primary&knob-text=Progress&selectedKind=AwesomeButtonProgress&selectedStory=Error%20Handling&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel).

It goes something like:

```
<Button
    ...
    onPress={(next) => {
        ...
        // on error
        next(false, 'Erros message');
    }}
/>
```

**Comment by walter-grace** [comment]
I am having issues getting a success on my AwesomeButtonProgress here is a segment of my code

_<AwesomeButtonProgress
  type="secondary"
  size="medium"
  ripple
  loadingLabel="HODLing..."
  resultLabel="Success"
 action={(element, next) => doSomethingThenCall(next)}
>
Refresh
</AwesomeButtonProgress>_


I tried using my function and it still wasn't giving me a success, any help much appreciated.
