### ISSUE TITLE
AWESOME BUTTON NOT WORKING WITH IONIC

### ISSUE THREAD

**Issue by NateWalchenbach** [rcaferati/react-awesome-button#135]
**I absolutely love this library. I wanted to try and use it with my ionic app and none of the props on the awesome buttons were working. Yet the buttons would still show and the animations would work. Any thoughts?**

**EX CODE:**
import React from "react";
import { AwesomeButton, AwesomeButtonProgress } from "react-awesome-button";
import "react-awesome-button/dist/styles.css";
import { IonApp, IonButton, IonPage, setupIonicReact } from "@ionic/react";
const App = () => {
  setupIonicReact({ mode: "md" });

  return (
    <IonApp>
      <IonButton
        onClick={() => {
          console.log("You clicked the ionic button");
        }}
      >
        Test
      </IonButton>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          height: "100vh",
        }}
      >
        <AwesomeButton
          type="primary"
          onPressed={() => {
            console.log("Clicked an awesome button");
          }}
        >
          PRIMARY
        </AwesomeButton>
        <AwesomeButtonProgress
          type="primary"
          onPress={(event: any, release: any) => {
            console.log(event.target);
            release();
          }}
        >
          ASYC BUTTON
        </AwesomeButtonProgress>
      </div>
    </IonApp>
  );
};

export default App;

**Comment by rcaferati** [comment]
Fixed on v7.0.5; thanks!
