### ISSUE TITLE
Error : 'Function components cannot be given refs'

### ISSUE THREAD

**Issue by CytrusGallium** [rcaferati/react-awesome-button#137]
Hello :) I'm getting the 'Function components cannot be given refs' error whenever I use AwesomeButton, the button seems fully functional, my React version is 18.2, is there a way to get rid of the error ?

**Comment by rcaferati** [comment]
Fixed on `v7.0.5`; thanks!

**Comment by CytrusGallium** [comment]
Works like a charm, Thank YOU !
