### ISSUE TITLE
The demo page is pointing to the React-Native component

### ISSUE THREAD

**Issue by Gabriel-Araujo** [rcaferati/react-awesome-button#16]
In the demo page (https://caferati.me/demo/react-awesome-button) has an error in the installation command. Be pointing to the React-Native component.

Installation
.sh
npm install --save react-native-awesome-button

Should be written
npm install --save react-awesome-button

**Comment by rcaferati** [comment]
Good catch. Thanks @Gabriel-Araujo o/
