### ISSUE TITLE
Can not disable an AwesomeButtonProgress

### ISSUE THREAD

**Issue by namdaoduy** [rcaferati/react-awesome-button#17]
AwesomeButtonProgress have no disabled prop?
I really need this :(

**Comment by danmouracunha** [comment]
Do you guys have any plans to implement this functionality? I really need this feature

**Comment by rcaferati** [comment]
Hey @danmouracunha, @namdaoduy. Thanks for the feed back. It wasn't persisting the disabled prop coming from the wrapper buttons. Fixed it on `5.0.1`
