### ISSUE TITLE
Programmatically click button

### ISSUE THREAD

**Issue by kmarkiewicz** [rcaferati/react-awesome-button#20]
I don't believe this is an issue, I'm just wondering how I can achieve this.
I want to be able to programmatically click the AwesomeButtonProgress. For example, I am using the button on a login page, when the user hits 'Enter' on their keyboard, I want the button to be triggered so that I can utilise the Button's progress animations.

How can I achieve this?
Below is the code from my failed attempt:

At the top of the class/component

    private loginButton: React.RefObject<HTMLInputElement>;

    constructor(props: any){
        super(props);
        this.loginButton = React.createRef();
        this._handleKeyPress = this._handleKeyPress.bind(this);
    }

The input onChange event
`
    _handleKeyPress = (event: any) => {
        if (event.key === 'Enter') {
            this.loginButton.current.click();
        }
    }
`
In the render method
`
    <AwesomeButtonProgress ref={(input: any) => this.loginButton = input} title={"Login"} type="primary" size="medium" action={(element: any, next: any) => this.handleLogin(next)}>
        Login
    </AwesomeButtonProgress>
`

Thanks!

**Comment by rcaferati** [comment]
Hey @kmarkiewicz. Good call! I've added a `fakePress` boolean prop to `6.0.0`. Thanks

**Comment by shamoons** [comment]
The `fakePress` doesn't seem to do anything?
