### ISSUE TITLE
Can't disable button

### ISSUE THREAD

**Issue by johneakin** [rcaferati/react-awesome-button#21]
I am disabling the button in the action

handleSearchClick = (button) => {
    console.log('button clicked')
    button.disabled=true;
  }

However the button is still visible.
In the DOM I can see:
button class="aws-btn aws-btn--facebook aws-btn--visible aws-btn--middle" role="button"

**Comment by harshmanwani** [comment]
I'm having the same problem. 
Is this the AwesomeButtonProgress?
I guess the disabling prop doesn't work on the Progress button.

**Comment by rcaferati** [comment]
@johneakin, @harshmanwani thanks for the feed back. It wasn't persisting the disabled prop coming from the wrapper buttons. Fixed on, fixed on `5.0.1`
