### ISSUE TITLE
AwesomeButton: onPress not triggered

### ISSUE THREAD

**Issue by giuliogallerini** [rcaferati/react-awesome-button#24]
The onPress event doesn't seem to trigger in the simple AwesomeButton.

**Comment by bnicholas** [comment]
it looks like onPress has been renamed action

**Comment by giuliogallerini** [comment]
I am gonna create a PR to update the docs, even if I find strange that it's called action and not just the native onClick event. @rcaferati Would it be an option to just have the native event name as prop?

**Comment by rcaferati** [comment]
Hey @giuliogallerini @bnicholas. Good catch. To avoid any breaking changes I've allowed `action` and `onPress` to be called from `v6.1.0`.

@giuliogallerini I'd rather not call it `onClick` as it's mainly not using a native `onClick` event and that could end up being misleading
