### ISSUE TITLE
6.1.0 All button hover effects seem to be malfunctioning

### ISSUE THREAD

**Issue by bchehraz** [rcaferati/react-awesome-button#27]
I'm not sure if it's just me, but ever since changing to 6.1.0 the hover effect on all the buttons no longer works as intended. It seems like the left side of the button no longer triggers the animation while the right side does. 

I switched to 6.0.0 and everything works as intended now. The only reason why I even changed to 6.1.0 was because `AwesomeButtonProgress` didn't have the prop `onPress` and was named `action` instead.

**Comment by GantMan** [comment]
ICK!  Same issue here.  Tons of errors :/

I was looking forward to using this button, but it appears to be failing pretty hard.  Docs are wrong, too.  Gonna switch.

**Comment by rcaferati** [comment]
@bchehraz Fixed on `6.1.2`,  thanks 🙌

@GantMan Indeed, the hover had a pretty annoying bump on the `6.1.0` move events. Fixed that and also did a bit of a review on the css background webkit flickering consistency. Thanks for mentioning it and if you find any specific issue on the docs feel free to point it out 🙌

**Comment by GantMan** [comment]
Woah!   Awesome!   I was afraid the project was abandoned.  Will def contribute back.   Is `next` still the second parameter of AwesomeProgress button?   If so, I'll fix docs on that, too.

**Comment by walter-grace** [comment]
I am having issues with the buttons here, the render time is extremely slow and the animation seems off. I can't display full link words in the progress button either, for example Generating won't fit. The buttons dont seem to be running as fast as the website here. Any suggestions?
