### ISSUE TITLE
Button overlaying above all other html elements

### ISSUE THREAD

**Issue by LukeStanislaus** [rcaferati/react-awesome-button#30]
Hi there,

I'm really happy with the button so far, but have a had a little issue with the button overlaying over modals, autocomplete/select boxes etc. Is there a workaround/fix for this?
If needed I am more than happy to supply a few code samples to show what I mean.

Thanks in advance,
Luke

**Comment by danmouracunha** [comment]
I had the same problem here. I'll send the pull request to solve this problem, need to fix the z-index in those classes
.aws-btn:before:
.aws-btn .aws-btn__content
.aws-btn .aws-btn__wrapper:before
