### ISSUE TITLE
[6.2.0] ParserError: Syntax Error at line: 1 (./node_modules/react-awesome-button/dist/styles.css)

### ISSUE THREAD

**Issue by ApacheEx** [rcaferati/react-awesome-button#41]
thanks for making awesome product 🚀 

just after upgrading, I've noticed:
![image](https://user-images.githubusercontent.com/1918108/68315871-23f26e00-00c1-11ea-924a-ff35221cd40c.png)

I'm using `"react-scripts": "3.2.0",`

**Comment by NamGungGeon** [comment]
I also see same error. Although I use pre-wrote css ('react-awesome-button/dist/themes/theme-indigo.css'), same error occur. This bug not occur when 'yarn start', but occur 'yarn build'.

**Comment by rcaferati** [comment]
Hey @ApacheEx, thanks for raising it. The bug was related to the pre-optiomization of the css files. I've removed it, just update to the latest version `v6.3.1`.
