### ISSUE TITLE
In Firefox buttons are gray.

### ISSUE THREAD

**Issue by FurkanTheHuman** [rcaferati/react-awesome-button#48]
![Screenshot from 2020-01-08 04 37 54](https://user-images.githubusercontent.com/22262446/71943218-f913bb80-31d0-11ea-9856-95fabdb03e0c.png)

It works in chrome but not in firefox. I thought something was  wrong with me, than I saw  [this](https://github.com/rcaferati/react-awesome-button/issues/14#issuecomment-557595683) guy. 
I am using firefox 70.0.1 (64-bit) in Elementary OS
This is the code, nothing special:
`
 <AwesomeButton   onPress={event=> this.tagClick(tagList,event)}  cssModule={AwesomeButtonStyles}  type="primary"  style={{width:"100%",padding:"0"}} >
            {tagList}
 </AwesomeButton>
`

**Comment by projeto-ura** [comment]
me too

**Comment by rcaferati** [comment]
Hey guys, thanks for raising it. It's fixed on `v6.4.1`. Unwanted `perserve-3d` on the outer element was causing the issue on Firefox when it was rendered as a Button.
