### ISSUE TITLE
Height custom style doesn't work

### ISSUE THREAD

**Issue by EliranGooner** [rcaferati/react-awesome-button#56]
I want to use aws-btn in several places in my Gatsby project but with a different variation in each place.
The default height works fine but whenever I try to change it nothing happens.
Added ```!important```, created another class with a different name but still to no avail.
I should note that I use the large size property on one of the buttons.

Any help would be appreciated.

**Comment by alonso-cadenas** [comment]
This comment may be helpful:
https://github.com/rcaferati/react-awesome-button/issues/12#issuecomment-597559712
