### ISSUE TITLE
Theme styles required?

### ISSUE THREAD

**Issue by smitch88** [rcaferati/react-awesome-button#7]
#### What

Great work!

Minor thing, I believe a newcomer to using the component may be confused by the README.md example versus the demo page. I think the README version needs another import for one of the the theme styles to show out of the box as expected.

i.e
```
import { AwesomeButton } from 'react-awesome-button';
import 'react-awesome-button/dist/styles.css';
import 'react-awesome-button/dist/themes/theme-blue.css';
```

**Comment by philohelp** [comment]
Nice one, thanks.

**Comment by rcaferati** [comment]
Hey @smitch88, thanks for the feedback. I've fully refactor the readme file o/
